#!/usr/bin/env bash
set -e
REPO_PATH=$HOME/.rmGoogleChromeSingletonLock
git clone https://github.com/WilliamSampaio/rmGoogleChromeSingletonLock.git $REPO_PATH
sudo cp $REPO_PATH/rmSingletonLock /usr/bin
sudo chmod +x /usr/bin/rmSingletonLock
sudo cp $REPO_PATH/rmsingletonlock.service /etc/systemd/system
sudo chmod 644 /etc/systemd/system/rmsingletonlock.service
sudo systemctl enable rmsingletonlock.service

sudo cp $REPO_PATH/rmSingletonLockUninstall /usr/bin
sudo chmod +x /usr/bin/rmSingletonLockUninstall
